### ISSUE TITLE
1.19 crash when using mod on server

### ISSUE THREAD

**Issue by complicitsalami** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#12]
Forge Version: 41.0.62
Game Version: 1.19
Mod Version: CNB-1.19-1.3.0.jar

My 1.19 server crashes when adding this mod, I also checked that I am also using the latest version of GeckoLib. Report below:

https://pastebin.com/ucKVFdnU

**Comment by mandychuu** [comment]
I am also having the same issue with an Apex server.

![image](https://user-images.githubusercontent.com/40618503/177696350-6262b944-96de-4340-86a6-7716694295ab.png)

**Comment by Dariensg** [comment]
This issue is solved by updating to 1.3.1.
