### ISSUE TITLE
Nether Sporelings are replaced by Overworld Sporelings

### ISSUE THREAD

**Issue by ghost** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#13]
Minecraft Version: 1.19
Forge Version: 41.0.61
Mod Version: CNB-1.19-1.3.0

When using the Nether Sporeling Spawn Egg and when exploring the Nether, I can only get Overworld Sporelings to spawn, and seemingly only the same red cap variant. 

(Sorry if I went about reporting this wrong, this is my first time using GitHub^^)

**Comment by Dariensg** [comment]
Could you please post a screenshot of the Sporelings? There are 3 categories: Friendly, Neutral, and Hostile. The Friendly and Neutral look fairly similar. Neutral Sporelings are Nether Sporelings, so I suspect you're mixing them up with the Friendly ones. The Warped and Crimson Sporelings can only be spawned in the corresponding Forest biomes. Let me know if there is still an issue!

**Comment by ghost** [comment]
Of course! I took a video instead though because it seemed easier to showcase the issue that way. Grabbed a free screen recorder that cut off the recording in the middle, but I waited till I found the little dude before starting it up again so you wouldn't have to watch me wander around aimlessly for a few more minutes haha. Sorry in advance for the quality, I haven't made a vid in years.

https://youtu.be/sh8u2GGjFmY

**Comment by ghost** [comment]
Oh also, not to spam but, why did you mark this issue as 1.18 rather than 1.19? I would have marked it myself but I'm unsure how to.

**Comment by Dariensg** [comment]
Oh, my bad! The 1.18 marking was just a mistake on my part, sorry. I'll take a look at the video in a moment.

**Comment by Dariensg** [comment]
Interesting! You're definitely right and something isn't working! I'll do some testing. Do you have any other mods installed?

**Comment by ghost** [comment]
When I initially made the post I also had a handful of others installed, but when I started recording I made sure that GeckoLib and CNB were all that I had just to see if it was caused by another mod and the same issue still happened. But just in case, here's my current modlist that I first noticed the issue with:

Appleskin 2.4.0
Aquaculture 2 2.4.2
Creatures and Beasts 1.3.0
Duckling 2.0.3
Infernal Expansion 2.5.0
JEI 11.0.0.206
Lava Monsters 1.0.11

(Also, no worries about the wrong flag! Sorry if I came off bad, I didn't mean to.)

**Comment by Dariensg** [comment]
You didn't come off bad at all! I have been able to replicate the issue in my Development environment, so I'll work on fixing it and try to get a fix out in the next few hours. I've got a somewhat busy day, but at the very latest I should be able to get it out within about 12 hours.

**Comment by Dariensg** [comment]
I actually discovered the issue very quickly and may have fixed it. Some of the approach to detecting biomes changed in 1.19 and I incorrectly switched to the new approach, so it was just always defaulting to the basic Sporeling. Testing my fix now. I probably won't be able to release it for a couple hours though.

**Comment by ghost** [comment]
No worries, take your time^^! Thank you very much though, and I'm glad to have been able to help!

**Comment by Dariensg** [comment]
Fixed in Release 1.3.3
