### ISSUE TITLE
Cactem are ticking entities and it's crashing my server

### ISSUE THREAD

**Issue by RFKreborn** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#19]
I mentioned this earlier and was told that it was a mod conflict with "It shall not tick", but i removed ISNT and the issue is still happening.  The crash happens when someone finds a wild cactem or when they log in to where a cactem has spawned. This happened with version 1.3.2 on 1.18.2.

[crash-2022-07-15_15.17.14-server.txt](https://github.com/Joo5h/Creatures_And_Beasts-Forge/files/9123374/crash-2022-07-15_15.17.14-server.txt)

**Comment by Dariensg** [comment]
If you remove all other mods besides Creatures and Beasts and GeckoLib, does it still occur? If not, please determine what mod is causing it.

**Comment by Dariensg** [comment]
Closing due to no response
