### ISSUE TITLE
Entities despawning

### ISSUE THREAD

**Issue by Infestidos** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#22]
Lizards and tamed entities do not despawn. Other untameable entities, despite a name tag, despawn.

**Comment by Infestidos** [comment]
I can only confirm this is happening for Cactems and the Overworld Sporelings.

**Comment by Dariensg** [comment]
Fixed by ff70eca81060adfc39e2138f4a33d4227c610c6d
