### ISSUE TITLE
Crash on Startup (1.19)

### ISSUE THREAD

**Issue by SalemRobin** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#24]
[crash-2022-07-30_00.43.55-fml.txt](https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/files/9224802/crash-2022-07-30_00.43.55-fml.txt)

**Comment by Dariensg** [comment]
Creatures and Beasts is not yet compatible with Forge past 41.0.63. I am going to be working on updating it to the Release Build over the next couple weeks, but I'm also in a busy time of the summer as my research comes to a close, so it might take me a bit. Sorry for the wait! I'll keep this issue open until it's done.

**Comment by Dariensg** [comment]
Totally forgot to come back and close this. I released the 41.1.0 version over a week ago. Sorry!
