### ISSUE TITLE
Carryon makes you crash if you go into f5

### ISSUE THREAD

**Issue by SucksAtstuff** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#25]
if you go into f5 while carrying one of the mobs itll crash the game

**Comment by Dariensg** [comment]
Please supply more information:
1. What MC version?
2. What Forge version?
3. What mob?
4. What other mods are installed?
5. Exact replication steps?

**Comment by SucksAtstuff** [comment]
What MC version?
1.18.2

What Forge version?
40.1.68

What mob?
lizard but im pretty sure other mobs do the same

What other mods are installed?
im playing on this modpack https://www.curseforge.com/minecraft/modpacks/cobbledcreate

Exact replication steps?
shift right click mob go f5 or if any player has it in render distance they crash as well

**Comment by Dariensg** [comment]
Totally forgot one thing. Could you please supply a crash report? This sounds like an interaction with another mod that isn’t working, given that you can’t pick up a lizard like that in this mod. So, some other mod is adding that capability, but it’s not working as that mod intends. I’ll have to see what’s causing it from a crash report.

**Comment by SucksAtstuff** [comment]
its using CarryOn it lets you pickup chests,mobs,spawners etc and it works i can pickup the mob but when i go into 3rd person it crashes and if anyone is near me with me in render distance when i do it they crash as well (we're all using the same mods)

but heres the crash report
[crash-2022-08-04_03.56.13-client.txt](https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/files/9256094/crash-2022-08-04_03.56.13-client.txt)

**Comment by Dariensg** [comment]
This is actually a GeckoLib issue. The issue has been identified and a Pull Request has been opened with GeckoLib to fix it. I'll close this issue once GeckoLib updates for the fix!

**Comment by SucksAtstuff** [comment]
alright thx

**Comment by Dariensg** [comment]
GeckoLib has now released a new version with the fix, so I'm going to close this issue now!
