### ISSUE TITLE
Heal spells split healing among tamed entities instead of healing all

### ISSUE THREAD

**Issue by VallenFrostweaver** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#28]
Minecraft 1.18.2
Forge 40.1.68
CnB 1.3.2

![image](https://user-images.githubusercontent.com/13642054/183962540-0eb39890-2662-47ad-a783-c305be3b93f5.png)
![image](https://user-images.githubusercontent.com/13642054/183962579-fe9f1ae2-3000-4c2d-9be6-5d54a14d4a1f.png)

**Comment by Dariensg** [comment]
Fixed by 899c5adfbe4f09a1596da6d7d4f83e48a476eb98
