### ISSUE TITLE
Incompatibility or issue with Improved Mobs mod

### ISSUE THREAD

**Issue by AnChedraui** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#33]
Just wanted to report an issue with improved mobs, previusly talked on their Github.

Modloader
Forge

Minecraft version
1.18.2

Modloader version
40.1.73

Mod version
1.10.15/1.10.14

TenshiLib version
1.6.9

Description
Crashing at running with message:

Improved Mobs Mod (improvedmobs) encountered an error during the common_setup event phase

  | java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.repairIngredient" is null

Logs

https://paste.gg/p/anonymous/db90f59edad84c0cbff0f5c35c170889

They answered:
Report to creaturesandbeasts. they returning null ingredient in one of their armor materials.

[crash-2022-08-21_19.54.01-fml.txt](https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/files/9409658/crash-2022-08-21_19.54.01-fml.txt)

**Comment by Handukar** [comment]
i have the exactly same problem :s

**Comment by BugmanBugman** [comment]
have this issue as well
https://github.com/Flemmli97/ImprovedMobs/issues/183

**Comment by Dariensg** [comment]
Solved by 0d9c10c4be656294a4c12ed31d15ab936625efd1
