### ISSUE TITLE
crash servers two times with Ticking entity

### ISSUE THREAD

**Issue by cfnnit** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#34]
https://pastebin.com/K77FhDfS

**Comment by Dariensg** [comment]
I may have figured out what's causing this and the next update should have an attempted fix. Given that I've never encountered this myself, I won't be able to definitively say that it is fixed, but I'm hoping it is.

**Comment by Dariensg** [comment]
Hopefully solved by 130f557f9e1ac42841084488a10e19f3313efec9
