### ISSUE TITLE
NullPointerException on server relating to CNB mobs

### ISSUE THREAD

**Issue by nekomaster1000** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#35]
[crash-2022-09-08_17.43.08-server.txt](https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/files/9530849/crash-2022-09-08_17.43.08-server.txt)
Mods used: https://www.curseforge.com/minecraft/modpacks/resurvival/files/3964358

**Comment by Dariensg** [comment]
Solved by 71860639492f7facb6d6c945ff8a691473f74548
