### ISSUE TITLE
Little Grebe ambient sound plays at player position

### ISSUE THREAD

**Issue by ChloeDawn** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#36]
**Mod version:**  1.4.0
**Forge version:** 40.1.80
**Game version:** 1.18.2

The ambient sound for little grebe plays at the player's position rather than the little grebe itself.
This can be caused by the sound file not being mono, as the positional audio system does not support stereo sound.

**Comment by Dariensg** [comment]
Solved by b27618526bdf74b5a985ffde3f14151744a5b9d2
