### ISSUE TITLE
Add to Modrinth

### ISSUE THREAD

**Issue by sylv256** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#43]
Please consider adding this mod to Modrinth to make it easier for modpack creators etc. on Modrinth.
An increasing number of mods are moving to Modrinth, especially as they recently added monetization support. Modrinth is a platform with better searching, API, and features for mod developers, and their community and developers are very welcoming to developers.

**Comment by Mirsario** [comment]
Someone forgot to close this issue, as I just came here from Modrinth - https://modrinth.com/mod/creatures-and-beasts
