### ISSUE TITLE
Nether Sporelings Not Being Tamed 1.19.2

### ISSUE THREAD

**Issue by ItsOnlyMagic** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#52]
Hi, I'm not sure if this is on purpose or if it's a bug, but the Nether Sporelings can't be tamed for me. Again, not sure if it's on purpose or not, but just wanted to know why I can't tame them. I'd really like to tame them, they're so cute

**Comment by Dariensg** [comment]
This is intended. Only the passive Sporelings from the Overworld are tameable. The neutral and hostile nether ones are not.
