### ISSUE TITLE
[1.19.2] Cactem only spawn in spectator mode

### ISSUE THREAD

**Issue by trashgryphon** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#56]
This is occurring in an install with no other mods.  Cactem spawn when you first load a new world or when you teleport, but then do not spawn as you traverse the world unless you are in spectator mode.  Changing the cactem spawn values doesn't seem to affect it.

**Comment by Dariensg** [comment]
I'm unable to replicate this. By flying around in Creative and occasionally applying the Glowing effect to all Cactems in range while in one of their spawn biomes, I'm clearly able to see that new ones are spawning. They're somewhat rare, but they're definitely there.
