### ISSUE TITLE
[1.19.2]: Geckolib3 updated to 3.1.40

### ISSUE THREAD

**Issue by SLO42** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#57]
Mod cnb requires geckolib3 between 3.1.27 and 3.1.39 (inclusive)

**Comment by Witixin1512** [comment]
For further context, your geckolib version range (not sure why it's locked from the end but that's a question for you, `[3.1.27,)` is valid toml iirc) excludes the latest version of geckolib, which is 3.1.40.

The error you get on bootup looks like this.
![image](https://user-images.githubusercontent.com/73248264/220954287-0990427f-c55a-4af4-99a7-8a57936a1dfb.png)

**Comment by Dariensg** [comment]
This was intentional, done to exclude any potentially breaking changes that could be introduced. Furthermore, 1.19.2 was meant to be unsupported, and therefore not receiving more updates. I'll make the bound for 4.0 exclusive!

**Comment by Dariensg** [comment]
Fixed by 39c6e0cea44219120313515e5fdff3f73018578f
