### ISSUE TITLE
[1.19.2] Spawn problem

### ISSUE THREAD

**Issue by Gonne5** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#59]
End whale, yeti and cindershell are not spawning, but the rest of the mobs do. I use the mod on aternos and i dont know how to solve the problem. 
I tried in vannila too and they dont spawn either.

**Comment by mintynoura** [comment]
End whale seems to be from a broken tag (#forge:is_end has been replaced with #forge:is_outer_end), making a datapack to replace the tag has made them spawn naturally for me. Yetis seem to spawn rarely but despawn very quickly, and Cindershells i haven't been able to find a fix for.

**Comment by mintynoura** [comment]
i have discovered that the tag might be broken because of another mod (biomesoplenty in my case), try to check your datapacks and make sure everything is formatted correctly

**Comment by Dariensg** [comment]
Fixed in 6be8496075aa8ecc6a9bebf7732eb8764aba840d
