### ISSUE TITLE
[1.19.2]Sometimes cactem drops nothing when bartering

### ISSUE THREAD

**Issue by ghost** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#61]
https://user-images.githubusercontent.com/129179911/236679010-9b5d4ec3-ab24-4a5c-8190-0430a7ab9a25.mp4

**Comment by Dariensg** [comment]
Do you have a mod list or a consistent way of replicating this?

**Comment by Dariensg** [comment]
I've been unable to replicate this.

**Comment by ghost** [comment]
> I've been unable to replicate this.

It can happen when only this mod is installed.Not each Cactem has this problem.If you can't replicate this on some cactem,all transaction with it will go with a swing.But if it is the Cactem with the problem,then every deal will fail.

Maybe you can keep trying on other cactems,the probability of triggering this bug is very high.

**Comment by ghost** [comment]
https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/assets/129179911/5b825aa1-5254-4de1-8979-151260228308

you can watch this video

**Comment by Dariensg** [comment]
Ok, I've been able to recreate it and am now working on a fix!
